### ISSUE TITLE
use of payment gateways as enrolment plugins is deprecated

### ISSUE THREAD

**Issue by danmarsden** [mamaeves/moodle-enrol_sber#2]
Moodle payment plugins should ideally be implmented as new payment gateway plugins:
https://docs.moodle.org/311/en/Payment_gateways

This means that the payment gateway can be used by a number of different plugins such as enrol_payment (core moodle payment plugin that allows multiple payment gateways to be used.) 

note this isn't a blocker for approval at this stage, but you might want to consider rewriting this plugin as a payment gateway one instead.

**Comment by mamaeves** [comment]
Hi, Dan! I did try using Payment API for another plugin (Orange Web Payment), but got stuck as the API is not fully documented and I was not able to clarify some of the things in PayPal payment gateway source code. At this point in time I would fix all other issues on this plugin and later start developement of payment gateway plugin.

**Comment by danmarsden** [comment]
yeah - I wrote a couple of payment gateways and battled away there - probably the harder part (for me anyway) was using more modern JS / AMD / promises etc. - but there are a few more payment gateways in the plugins db now that you can use as examples that should make it a bit easier.

closing this - it's not really a bug, was more just FYI.
